export const exportedPythonGame = `"""Stoneveil Valley — native game source generated by Blocksmith Studio.

The world is deterministic and streams chunks around the player forever.
"""
from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController
import json
import math
import sys
from pathlib import Path

BUNDLE_DIR = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
PROJECT = json.loads((BUNDLE_DIR / "project.blocksmith.json").read_text(encoding="utf-8"))
WORLD = PROJECT.get("world", {})
CHUNK_SIZE = max(6, min(16, int(WORLD.get("chunkSize", 8))))
RENDER_DISTANCE = max(1, min(3, int(WORLD.get("renderDistance", 2))))
WORLD_SEED = int(WORLD.get("seed", 481516))
BIOME = WORLD.get("biome", "Meadow")
WEATHER = WORLD.get("weather", "Clear")
WEATHER_INTENSITY = int(WORLD.get("weatherIntensity", 65))
WIND_SPEED = int(WORLD.get("windSpeed", 28))
TIME_OF_DAY = float(WORLD.get("timeOfDay", 14))

app = Ursina(
    title=PROJECT.get("name", "Stoneveil Valley"),
    borderless=False,
    fullscreen=False,
    development_mode=False,
)
window.color = color.rgb(20, 24, 21)
window.exit_button.visible = False
window.fps_counter.enabled = False

BLOCK_COLORS = {
    "Grass": color.rgb(105, 133, 63), "Dirt": color.rgb(126, 88, 58),
    "Stone": color.rgb(123, 128, 124), "Sand": color.rgb(203, 176, 113),
    "Water": color.rgba(69, 139, 157, 210), "Bedrock": color.rgb(59, 61, 59),
}
selected_material = "Grass"


def terrain_height(x, z):
    broad = math.sin((x + WORLD_SEED * .13) * .15) * 1.2
    broad += math.cos((z - WORLD_SEED * .07) * .17) * 1.05
    detail = math.sin((x + z) * .42 + WORLD_SEED) * .38
    detail += math.cos((x - z) * .31) * .3
    multiplier = 1.65 if BIOME == "Highlands" else .55 if BIOME == "Desert" else 1
    return max(-1, min(5, math.floor((broad + detail) * multiplier)))


class Voxel(Button):
    """A placeable and breakable one-meter block owned by a streamed chunk."""

    def __init__(self, position=(0, 0, 0), material="Grass", breakable=True, chunk=None):
        tint = BLOCK_COLORS.get(material, BLOCK_COLORS["Grass"])
        super().__init__(
            parent=scene, position=position, model="cube", origin_y=.5,
            texture="white_cube", color=tint,
            highlight_color=color.rgba(235, 190, 100, 255), collider="box",
        )
        self.material_name = material
        self.breakable = breakable
        self.chunk = chunk

    def input(self, key):
        if not self.hovered:
            return
        if key == "left mouse down" and self.breakable:
            destroy(self)
        elif key == "right mouse down":
            Voxel(position=self.position + mouse.normal, material=selected_material)


class InfiniteWorld:
    """Loads a square of deterministic chunks and unloads distant chunks."""

    def __init__(self):
        self.loaded = {}
        self.center = None

    def create_chunk(self, cx, cz):
        key = (cx, cz)
        entities = []
        surface_material = "Sand" if BIOME == "Desert" else "Grass"
        for local_z in range(CHUNK_SIZE):
            for local_x in range(CHUNK_SIZE):
                x = cx * CHUNK_SIZE + local_x
                z = cz * CHUNK_SIZE + local_z
                surface = terrain_height(x, z)
                entities.append(Voxel((x, surface, z), surface_material, chunk=key))
                entities.append(Voxel((x, surface - 1, z), "Dirt", chunk=key))
                entities.append(Voxel((x, surface - 2, z), "Stone", chunk=key))
        self.loaded[key] = entities

    def stream(self, position):
        cx = math.floor(position.x / CHUNK_SIZE)
        cz = math.floor(position.z / CHUNK_SIZE)
        if self.center == (cx, cz):
            return
        self.center = (cx, cz)
        wanted = {
            (x, z)
            for z in range(cz - RENDER_DISTANCE, cz + RENDER_DISTANCE + 1)
            for x in range(cx - RENDER_DISTANCE, cx + RENDER_DISTANCE + 1)
        }
        for key in wanted - set(self.loaded):
            self.create_chunk(*key)
        for key in set(self.loaded) - wanted:
            for block in self.loaded.pop(key):
                destroy(block)
        chunk_label.text = f"INFINITE WORLD   CHUNK {cx}, {cz}   {len(self.loaded)} LOADED"


world = InfiniteWorld()
sky_colors = {
    "Clear": color.rgb(166, 190, 170), "Rain": color.rgb(112, 135, 137),
    "Snow": color.rgb(180, 193, 195), "Storm": color.rgb(72, 82, 89),
}
Sky(color=sky_colors.get(WEATHER, sky_colors["Clear"]))
sun = DirectionalLight(shadows=True)
sun.look_at(Vec3(1, -1, -1))
sun.color = color.rgb(255, 196, 139) if TIME_OF_DAY < 8 or TIME_OF_DAY > 18 else color.rgb(255, 244, 207)
AmbientLight(color=color.rgba(150, 150, 150, 90))
player = FirstPersonController(position=(1, 8, 1), speed=5, jump_height=1.25)
player.cursor.color = color.rgb(230, 177, 76)

help_text = Text(
    "WASD move   SPACE jump   LEFT break   RIGHT place   1-6 choose block",
    origin=(0, 0), y=-.47, scale=.72, color=color.rgba(235, 238, 233, 180)
)
chunk_label = Text("GENERATING WORLD...", x=-.86, y=.46, scale=.62, color=color.rgba(230, 235, 228, 170))
weather_label = Text(f"{WEATHER.upper()}   {int(TIME_OF_DAY):02d}:00", x=.68, y=.46, scale=.62, color=color.rgba(230, 235, 228, 170))
weather_particles = []
if WEATHER in ("Rain", "Snow", "Storm"):
    particle_count = min(260, 40 + WEATHER_INTENSITY * 2)
    for index in range(particle_count):
        snow = WEATHER == "Snow"
        drop = Entity(
            model="cube", color=color.rgba(225, 240, 242, 205) if snow else color.rgba(150, 196, 211, 175),
            scale=(.035, .035, .035) if snow else (.018, .42, .018),
            position=(((index * 37) % 42) - 21, ((index * 19) % 22) + 2, ((index * 53) % 42) - 21),
        )
        weather_particles.append(drop)


def add_authored_objects():
    for item in PROJECT.get("scene", []):
        if not item.get("visible", True):
            continue
        kind = item.get("kind")
        position = tuple(round(value) for value in item.get("position", [0, 0, 0]))
        if kind == "block":
            Voxel(position, item.get("material", "Grass"))
        elif kind in ("weapon", "item", "custom"):
            Entity(
                model="cube", texture="white_cube", position=position,
                scale=(.3, 1.2, .2) if kind == "weapon" else (.7, .7, .2),
                color=color.hex(item.get("color", "#a0a5a2")), collider="box"
            )


add_authored_objects()
world.stream(player.position)


def input(key):
    global selected_material
    slots = {"1": "Grass", "2": "Dirt", "3": "Stone", "4": "Sand", "5": "Water", "6": "Bedrock"}
    if key in slots:
        selected_material = slots[key]
        help_text.text = f"Selected: {selected_material}    LEFT break   RIGHT place"
    if key == "escape":
        application.quit()


def update():
    world.stream(player.position)
    snow = WEATHER == "Snow"
    fall_speed = 2.4 if snow else 15.0
    wind = WIND_SPEED * (.008 if snow else .014)
    for index, particle in enumerate(weather_particles):
        particle.y -= time.dt * fall_speed
        particle.x += time.dt * wind
        if particle.y < player.y - 2 or abs(particle.x - player.x) > 24 or abs(particle.z - player.z) > 24:
            particle.position = (
                player.x + ((index * 37) % 42) - 21,
                player.y + ((index * 19) % 20) + 8,
                player.z + ((index * 53) % 42) - 21,
            )


app.run()
`
