export const exportedPythonGame = `"""Stoneveil Valley — generated by Blocksmith Studio.

Run with:  python main.py
Build with: build_windows.bat
"""
from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController
import json
import sys
from pathlib import Path

app = Ursina(
    title="Stoneveil Valley",
    borderless=False,
    fullscreen=False,
    development_mode=False,
)
window.color = color.rgb(20, 24, 21)
window.exit_button.visible = False
window.fps_counter.enabled = False

BLOCK_COLORS = {
    "Grass": color.rgb(105, 133, 63),
    "Dirt": color.rgb(126, 88, 58),
    "Stone": color.rgb(123, 128, 124),
    "Sand": color.rgb(203, 176, 113),
    "Water": color.rgba(69, 139, 157, 210),
    "Bedrock": color.rgb(59, 61, 59),
}
selected_material = "Grass"


class Voxel(Button):
    """A placeable and breakable one-meter world block."""

    def __init__(self, position=(0, 0, 0), material="Grass", breakable=True):
        super().__init__(
            parent=scene,
            position=position,
            model="cube",
            origin_y=.5,
            texture="white_cube",
            color=BLOCK_COLORS.get(material, BLOCK_COLORS["Grass"]),
            highlight_color=color.rgba(235, 190, 100, 255),
            collider="box",
        )
        self.material_name = material
        self.breakable = breakable

    def input(self, key):
        if not self.hovered:
            return
        if key == "left mouse down" and self.breakable:
            destroy(self)
        if key == "right mouse down":
            Voxel(position=self.position + mouse.normal, material=selected_material)


def make_tree(position):
    x, y, z = position
    for height in range(3):
        Voxel((x, y + height, z), "Dirt")
    for dx, dy, dz in [
        (0, 3, 0), (1, 3, 0), (-1, 3, 0), (0, 3, 1),
        (0, 3, -1), (0, 4, 0), (1, 4, 0), (0, 4, 1)
    ]:
        block = Voxel((x + dx, y + dy, z + dz), "Grass")
        block.color = color.rgb(65, 105, 54)


def load_world():
    bundle_dir = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent))
    project_path = bundle_dir / "project.blocksmith.json"
    data = json.loads(project_path.read_text(encoding="utf-8"))

    # A flat editable foundation is generated automatically.
    for z in range(-10, 10):
        for x in range(-12, 12):
            Voxel((x, -1, z), "Grass", breakable=False)

    for item in data.get("scene", []):
        kind = item.get("kind")
        pos = tuple(round(value) for value in item.get("position", [0, 0, 0]))
        if kind == "block" and item.get("visible", True):
            Voxel(pos, item.get("material", "Grass"))
        elif kind == "tree" and item.get("visible", True):
            make_tree(pos)


load_world()
Sky(color=color.rgb(166, 190, 170))
sun = DirectionalLight(shadows=True)
sun.look_at(Vec3(1, -1, -1))
AmbientLight(color=color.rgba(150, 150, 150, 90))
player = FirstPersonController(position=(1, 2, 1), speed=5, jump_height=1.25)
player.cursor.color = color.rgb(230, 177, 76)

help_text = Text(
    "WASD move   SPACE jump   LEFT break   RIGHT place   1-6 choose block",
    origin=(0, 0), y=-.47, scale=.72, color=color.rgba(235, 238, 233, 180)
)


def input(key):
    global selected_material
    slots = {"1": "Grass", "2": "Dirt", "3": "Stone", "4": "Sand", "5": "Water", "6": "Bedrock"}
    if key in slots:
        selected_material = slots[key]
        help_text.text = f"Selected: {selected_material}    LEFT break   RIGHT place"
    if key == "escape":
        application.quit()


app.run()
`
